### PR TITLE
added nagivation cache helper

### PR DESCRIPTION
**Pull request by allandegnan**
### What
We are adding a navigation cache to the dp-frontend-* repos, but this is very repetitive code, so consolidated it here and consumed it on dp-frontend-feedback-controller

### How to review
Some thing to consider:

- Folder structure.  I put external helper / client in pkg.  I put the inner-workings in internal, which can't be consumed outside of this repo.
- Ergo, the interface and the helper are probably the most important things to get right here.
- Mostly this is copied from the live version within the dp-frontend-homepage-controller.

### Who can review
!me

### CODE REVIEW

**Comment by allandegnan** [comment]
It might be we pull this into a different library.  Don't love the interface, but setting up a working example for feedback.

**Review by nshumoogum — APPROVED** [review]
Could do with documentation around how to interact with client but happy to approve for now to unblock use of library in our apps

Also your right probably deserves it's own library

**Comment by allandegnan** [comment]
How about we just create a `dp-frontend-cache-helper` repo and stick it in there?  We could make the name more specific, but I've just assumed the footer, and anything else cached by the generic templates in `dp-renderer` could be cached the same way?

**Comment by nshumoogum** [comment]
Yeah that does sound more appeasing to me; there are other caches we may want to implement later and could require something similar and could reuse this new library

**Pull request closed without merging**
